### ISSUE TITLE
python2-miniupnpc idea

### ISSUE THREAD

**Issue by kewlfft** [M0Rf30/PKGBUILD#2]
I am the comaintainer of python-miniupnpc.

I believe we could merge the two into one package base with the 2 variations, what do you think?

Thanks

**Comment by M0Rf30** [comment]
I'm thinking about in the past days. Of course

**Comment by M0Rf30** [comment]
I could male you as a co-maintainer with write read permissions

**Comment by kewlfft** [comment]
Yes please I would like to be comaintainer, I use the python package and could update it when needed, thanks.
Do you know how to proceed to replace python-miniupnpc ? Does it needs to be removed first ? 
I am only comaintainer, I suggested the merge to the maintainer as well but haven’t had a response yet.

**Comment by M0Rf30** [comment]
Now you are a comaintainer of python2-miniupnpc. Could you make me comaintainer of yours? You have to push a PKGBUILD like this one:
[example](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=python-sounddevice)

**Comment by kewlfft** [comment]
Unfortunately I don't have the rights to add co-maintainers, you should ask the maintainer to add you
I can certainly push the new pkgbuild but won't it conflict with yours?

**Comment by kewlfft** [comment]
I implemented the PKGBUILD but it conflicts with your package, I cannot push it it gets rejected.
I think you can delete yours and you will get co-maintainance of the python-miniupnpc. The current maintainer was fine to share or even give someone else full maintainance.

**Comment by M0Rf30** [comment]
please retry now

**Comment by kewlfft** [comment]
same 
remote: error: cannot overwrite package: python2-miniupnpc

**Comment by kewlfft** [comment]
just pushing my commit python-miniupnpc with the new PKGBUILD
```
remote: error: cannot overwrite package: python2-miniupnpc
remote: error: hook declined to update refs/heads/master
To ssh://aur.archlinux.org/python-miniupnpc.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'ssh://aur@aur.archlinux.org/python-miniupnpc.git'
```

**Comment by M0Rf30** [comment]
I've made a request

**Comment by kewlfft** [comment]
I will contact the maintainer on another email address I have for him as well.
done.

**Comment by kewlfft** [comment]
Are you waiting co-maintainance on 'python-' and you will delete 'python2-' ?

**Comment by M0Rf30** [comment]
pkgbase will be python-miniupnpc so I'm waiting for union or co-maintaining

**Comment by kewlfft** [comment]
Ok have you made a merge request ?

**Comment by kewlfft** [comment]
You should be co-maintainer now.
Are you ok to merge?

**Comment by kewlfft** [comment]
I’m sending you the merge request this is the way to go - thanks

**Comment by M0Rf30** [comment]
Done, I've included i686 arch for archlinux32 fork, required makedeps, a mention for latest maintainers and some cleanup. Good job man ! :D

**Comment by M0Rf30** [comment]
https://github.com/M0Rf30/PKGBUILD/commit/689c990649c1680715da118cb58cb84418c724df

**Comment by kewlfft** [comment]
_Question_: the copy of the source to a different py2 directory, the separate make, were not necessary then?

**Comment by M0Rf30** [comment]
here the content of the two packages:
```
morfeo@unknown ~> yay -Ql python2-miniupnpc
python2-miniupnpc /usr/
python2-miniupnpc /usr/lib/
python2-miniupnpc /usr/lib/python2.7/
python2-miniupnpc /usr/lib/python2.7/site-packages/
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc-2.0-py2.7.egg-info/
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc-2.0-py2.7.egg-info/PKG-INFO
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc-2.0-py2.7.egg-info/SOURCES.txt
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc-2.0-py2.7.egg-info/dependency_links.txt
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc-2.0-py2.7.egg-info/top_level.txt
python2-miniupnpc /usr/lib/python2.7/site-packages/miniupnpc.so
python2-miniupnpc /usr/share/
python2-miniupnpc /usr/share/licenses/
python2-miniupnpc /usr/share/licenses/python2-miniupnpc/
python2-miniupnpc /usr/share/licenses/python2-miniupnpc/LICENSE
```
```
morfeo@unknown ~> yay -Ql python-miniupnpc
python-miniupnpc /usr/
python-miniupnpc /usr/lib/
python-miniupnpc /usr/lib/python3.6/
python-miniupnpc /usr/lib/python3.6/site-packages/
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc-2.0-py3.6.egg-info/
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc-2.0-py3.6.egg-info/PKG-INFO
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc-2.0-py3.6.egg-info/SOURCES.txt
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc-2.0-py3.6.egg-info/dependency_links.txt
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc-2.0-py3.6.egg-info/top_level.txt
python-miniupnpc /usr/lib/python3.6/site-packages/miniupnpc.cpython-36m-x86_64-linux-gnu.so
python-miniupnpc /usr/share/
python-miniupnpc /usr/share/licenses/
python-miniupnpc /usr/share/licenses/python-miniupnpc/
python-miniupnpc /usr/share/licenses/python-miniupnpc/LICENSE
```
So it's not needed

**Comment by kewlfft** [comment]
understood thanks
