### ISSUE TITLE
Moving Distrobox to [community]

### ISSUE THREAD

**Issue by Antiz96** [M0Rf30/PKGBUILD#26]
Hi,

I'm contacting you through this issue *(sorry I couldn't find another way to do so)* to tell you that I plan to move the `distrobox` AUR package to Arch's [community] repo. I'll take over the maintenance of the PKGBUILD once moved there but you'll obviously still be credited as a contributor in it.

Is that fine for you? :)
  
Poke @89luca89 so you aware of this ;)

**Comment by M0Rf30** [comment]
No problem for me. Please keep rolling :smile:

**Comment by Antiz96** [comment]
Cool! Thanks a lot for your quick answer :)

I'm gonna write a comment on the distrobox AUR web page to let people know about this.
