### ISSUE TITLE
Subsonic Licence

### ISSUE THREAD

**Issue by robozman** [M0Rf30/PKGBUILD#5]
The PKGBUILD for subsonic lists the licence as GPL.  Subsonic has become closed source as of the latest version. http://forum.subsonic.org/forum/viewtopic.php?f=4&t=16604#p71128

**Comment by M0Rf30** [comment]
Should I consider as a CUSTOM or COMMERCIAL license in your opininion?

**Comment by robozman** [comment]
Base on the PKGBUILDs for a few other applications on the aur(Namely Plex and Teamspeak 3 server software) with similar profit models, CUSTOM looks like the way to go.

**Comment by M0Rf30** [comment]
Ok I will update the PKGBUILD with custom license. Thanks man
