### ISSUE TITLE
Winetricks-git depends on wine and wine-git is not available

### ISSUE THREAD

**Issue by C0rn3j** [M0Rf30/PKGBUILD#6]
So perhaps just add 'wine-git' as a possibility along with 'wine'? I didn't test this but I don't see why it wouldn't work.

**Comment by M0Rf30** [comment]
Wine is a big package to compile, so winetricks-git relays always on official repo package.
wine-git is in AUR, However feel free to use wine-git in AUR. If wine-git contains "provides=wine" or something similar, then winetricks-git will work with no issues
